name: Webpack and Pages Deploy

on:
  push:
    branches: [ "node" ]
  pull_request:
    branches: [ "node" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Cache Webpack Build
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: Webpack-Build
      with:
        path: ~/.npm
        key: WebPackBuildCache

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npx webpack
